name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sentiment-analysis:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 4.6.2

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test --configuration Release --no-restore

      - name: Run Sentiment Analysis
        run: dotnet run --project SentimentAnalysis.csproj
