

name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: desktop-app
        path: ./publish

    - name: Run SentimentAnalysis program
      run: dotnet run --configuration Release --project SentimentAnalysis/SentimentAnalysis.csproj
